{{- if .Values.traefik.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "k8s-auto-loadbalancer.fullname" . }}
  labels:
    {{- include "k8s-auto-loadbalancer.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.traefik.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.traefik.ingressRoute.routes }}
    - match: {{ .match }}
      kind: {{ .kind }}
      priority: {{ .priority }}
      services:
        {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
        {{- end }}
      {{- if and $.Values.traefik.middlewares.enabled $.Values.traefik.middlewares.configurations }}
      middlewares:
        {{- range $.Values.traefik.middlewares.configurations }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- with .Values.traefik.ingressRoute.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}