{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoute.name }}
  labels:
    {{- include "k8s-auto-loadbalancer.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.ingressRoute.routes }}
    - match: {{ .match }}
      kind: {{ .kind }}
      priority: {{ .priority }}
      services:
        {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
          {{- if .scheme }}
          scheme: {{ .scheme }}
          {{- end }}
        {{- end }}
      {{- with .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- with .Values.ingressRoute.tls }}
  tls:
    certResolver: {{ .certResolver }}
  {{- end }}
{{- end }}