{{- if and .Values.traefik.middlewares.enabled .Values.traefik.middlewares.configurations }}
{{- range .Values.traefik.middlewares.configurations }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "k8s-auto-loadbalancer.fullname" $ }}-{{ .name }}
  labels:
    {{- include "k8s-auto-loadbalancer.labels" $ | nindent 4 }}
spec:
  {{- omit . "name" | toYaml | nindent 2 }}
{{- end }}
{{- end }}