services:
  www:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/www/Dockerfile
      args:
        - PROJECT=www
    restart: always
    ports:
      - 3000:3000
    networks:
      - kalb
  
networks:
  kalb:
    external: true