---
additionalArguments:
  # Cloudflare Annotations
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=cloudflare.pebble609@passinbox.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-cloudflare.json

logs:
  # Configure log settings here...
  general:
    # level: ERROR
    level: DEBUG

ports:
  # Configure your entrypoints here...
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
      certResolver: cloudflare

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: CLOUDFLARE_EMAIL
        name: cloudflare-secret
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: CLOUDFLARE_APIKEY
        name: cloudflare-secret

# Disable Dashboard
ingressRoute:
  dashboard:
    enabled: false

# Persistent Storage
persistence:
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.36.1
      command:
        [
          'sh',
          '-c',
          'touch /ssl-certs/acme-cloudflare.json; chmod -Rv 600 /ssl-certs/*'
        ]
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

# Enable IngressClass for Traefik
ingressClass:
  enabled: true
  isDefaultClass: true

# Metrics
metrics:
  prometheus:
    addRoutersLabels: true
    addEntryPointsLabels: true
    addServicesLabels: true

# Plugins
experimental:
  plugins:
    coraza:
      moduleName: github.com/jcchavezs/coraza-http-wasm-traefik
      version: v0.2.2