# Global settings
global:
  nameOverride: 'k8s-auto-loadbalancer'
  fullnameOverride: 'k8s-auto-loadbalancer'

# Deployment configuration
deployment:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 600
  image:
    repository: pungrumpy/kalb
    tag: 0250124674c1a5e676a72c5a2d7c882511a6567b
    pullPolicy: IfNotPresent
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

# Probes configuration
probes:
  readiness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 3
    failureThreshold: 3
  liveness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Autoscaling configuration
autoscaling:
  horizontal:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 1
            periodSeconds: 15
  vertical:
    enabled: false
    updateMode: 'Off'
    minAllowed:
      cpu: 100m
      memory: 256Mi
    maxAllowed:
      cpu: 500m
      memory: 768Mi

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ''

# ConfigMap configuration
configMap:
  data: {}

# Secrets configuration
secrets:
  secretName: webapp-secret

# Resource management
resourceManagement:
  quota:
    enabled: true
    hard:
      requests.cpu: '1'
      limits.cpu: '2'
      requests.memory: 2Gi
      limits.memory: 4Gi
  limitRange:
    enabled: true
    defaultLimit:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi

# Traefik configuration
traefik:
  ingressRoute:
    enabled: true
    entryPoints:
      - websecure
    routes:
      - match: Host(`pungrumpy.xyz`)
        kind: Rule
        priority: 10
        services:
          - name: k8s-auto-loadbalancer
            port: 80
    tls:
      certResolver: cloudflare
  middlewares:
    enabled: true
    configurations:
      - name: ratelimit
        spec:
          rateLimit:
            average: 100
            burst: 200
      - name: retry
        spec:
          retry:
            attempts: 3
            initialInterval: '100ms'

# Pod Disruption Budget configuration
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable: 0
