# Global settings
global:
  nameOverride: 'k8s-auto-loadbalancer'
  fullnameOverride: 'k8s-auto-loadbalancer'

# Deployment configuration
deployment:
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 600
  image:
    repository: pungrumpy/kalb
    tag: 8e0b0e304954aef9c2e988be38a40c68c4e9f52c
    pullPolicy: IfNotPresent
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      cpu: 300m
      memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-type
                operator: In
                values:
                  - high-cpu

# Probes configuration
probes:
  readiness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 5
    periodSeconds: 3
    failureThreshold: 3
  liveness:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Autoscaling configuration
autoscaling:
  horizontal:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
      scaleUp:
        stabilizationWindowSeconds: 0
        policies:
          - type: Percent
            value: 100
            periodSeconds: 15
          - type: Pods
            value: 1
            periodSeconds: 15
  vertical:
    enabled: false
    updateMode: 'Off'
    minAllowed:
      cpu: 100m
      memory: 256Mi
    maxAllowed:
      cpu: 500m
      memory: 768Mi

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ''

# ConfigMap configuration
configMap:
  data: {}

# Secrets configuration
secrets:
  secretName: webapp-secret

# Resource management
resourceManagement:
  quota:
    enabled: true
    hard:
      requests.cpu: '2'
      limits.cpu: '4'
      requests.memory: 4Gi
      limits.memory: 8Gi
  limitRange:
    enabled: true
    defaultLimit:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 50m
      memory: 256Mi

# Traefik configuration
traefik:
  ingressRoute:
    enabled: true
    entryPoints:
      - websecure
    routes:
      - match: Host(`pungrumpy.xyz`)
        kind: Rule
        priority: 10
        services:
          - name: k8s-auto-loadbalancer
            port: 80
    tls:
      certResolver: cloudflare
  middlewares:
    enabled: true
    configurations:
      - name: ratelimit
        spec:
          rateLimit:
            average: 100
            burst: 400
      - name: retry
        spec:
          retry:
            attempts: 2
            initialInterval: '100ms'
      - name: circuit-breaker
        spec:
          circuitBreaker:
            expression: 'ResponseCodeRatio(500, 600, 0, 600) > 0.25'
      - name: buffering
        spec:
          buffering:
            maxRequestBodyBytes: 2097152
            memRequestBodyBytes: 2097152
            maxResponseBodyBytes: 2097152
            memResponseBodyBytes: 2097152
            retryExpression: 'IsNetworkError() && Attempts() <= 2'

# Pod Disruption Budget configuration
podDisruptionBudget:
  enabled: true
  minAvailable: 1
  maxUnavailable: 0
