replicaCount: 2

image:
  repository: pungrumpy/kalb
  tag: 494818ebeb64b21ce423301e1b0d1961aab6616a
  pullPolicy: IfNotPresent

nameOverride: 'k8s-auto-loadbalancer'
fullnameOverride: 'k8s-auto-loadbalancer'

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

secrets:
  secretName: webapp-secret

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 300

nodeSelector: {}

tolerations: []

affinity: {}

configMap:
  data: {}

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

progressDeadlineSeconds: 600

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10

# Ingress routing with Traefik
ingressRoute:
  enabled: true
  name: k8s-auto-loadbalancer
  entryPoints:
    - websecure
  routes:
    - match: Host(`pungrumpy.xyz`)
      kind: Rule
      priority: 10
      services:
        - name: k8s-auto-loadbalancer
          port: 80
  tls:
    certResolver: cloudflare
